### ISSUE TITLE
when i put the mod i have some blocks have textures oh no

### ISSUE THREAD

**Issue by intrxhyevert** [Zelaux/ByteLogicMod#12]
some blocks have textures oh no

**Comment by Zelaux** [comment]
Can you show screenshot and say which blocks with oh no?

**Comment by fufu1437** [comment]
![Screenshot_2023-08-26-21-24-17-22_13f989b68d7412e5a177fb13b36ac66f.jpg](https://github.com/Zelaux/ByteLogicMod/assets/128881350/fef77a3f-b2f1-45d4-946a-8a4b3ca97424)This box shows a bug

**Comment by Zelaux** [comment]
Perhaps this is caused by other mods?

**Comment by intrxhyevert** [comment]
нет

вс, 10 сент. 2023 г., 00:30 Zelaux ***@***.***>:

**Comment by Zelaux** [comment]
This is a very strange bug, it has never happened to me, but for some reason it happened to someone

**Comment by fufu1437** [comment]
![Screenshot_2023-09-16-11-14-12-39_13f989b68d7412e5a177fb13b36ac66f.jpg](https://github.com/Zelaux/ByteLogicMod/assets/128881350/9aedebc9-7c52-45ef-94a5-473135e8385b)![Screenshot_2023-09-16-11-14-17-95_13f989b68d7412e5a177fb13b36ac66f.jpg](https://github.com/Zelaux/ByteLogicMod/assets/128881350/c481300f-e1d1-4f09-b0ad-38397da92045)
All mods are turned off and still cannot be displayed normally

**Comment by Zelaux** [comment]
I guess fixed
