### ISSUE TITLE
Incorrect icon(s)?

### ISSUE THREAD

**Issue by Djspac3** [Zelaux/ByteLogicMod#14]
I'm playing on the newest mobile ver for context 
But looking at what to use confuses me with a switch icon not looking like the switch or LITTERALY EVERY OTHER one i tried for the sort time i played with the mod 
Also another mod I'm using (im gona check it after making this) shows A HOLE LOT of the error textures for the interactions oddly it seems like a object being used for the wiring to work but still that doesn't change that

**Comment by Djspac3** [comment]
A video file showing what I mean [drive link](https://drive.google.com/file/d/1VApTjoA5qeDhwMhQqwVC19d_Z-rXU8xM/view?usp=drivesdk)

**Comment by Zelaux** [comment]
Fixed
