### ISSUE TITLE
Game crashes when attempting to get info about block

### ISSUE THREAD

**Issue by vivvyinks** [Zelaux/ByteLogicMod#9]
**Describe the bug**
Instantaneous crash on attempting to click '?' button on any byte-logic block.

**To Reproduce**
1. Launch Mindustry with ByteLogicMod installed.
2. Make a new world or launch an existing one with the mod.
3. Select a byte logic block.
4. Click the '?' button.

**Expected behavior**
Block info screen should appear.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 10.0.19044 Build 19044

**Comment by vivvyinks** [comment]
crash report attached
[crash-report-01_17_2023_12_38_46.txt](https://github.com/Zelaux/ByteLogicMod/files/10439468/crash-report-01_17_2023_12_38_46.txt)

**Comment by Zelaux** [comment]
v141.1 moment

**Comment by Michael-R-9** [comment]
On android version 7 141.2, these crashes also occur when I try to click on the question icon
